vich_uploader:
    db_driver: orm

    mappings:
       document:
           uri_prefix: /document/devis
           upload_destination: '%kernel.project_dir%/public/document/devis'
           namer: Vich\UploaderBundle\Naming\OrignameNamer
